export const populerData = {
    geo: [
      { label: "Lampung Tengah", value: "lampung-tengah", description: "A district in Lampung Province" },
      { label: "Jakarta", value: "jakarta", description: "The capital city of Indonesia" },
      { label: "Surabaya", value: "surabaya", description: "A metropolitan city in East Java" },
      { label: "Bandung", value: "bandung", description: "A city in West Java known for its technology scene" },
      { label: "Yogyakarta", value: "yogyakarta", description: "A special region known for its cultural heritage" },
      { label: "Medan", value: "medan", description: "A major city in North Sumatra" },
      { label: "Makassar", value: "makassar", description: "The largest city in South Sulawesi" },
      { label: "Palembang", value: "palembang", description: "A city famous for its traditional dish, Pempek" },
      { label: "Denpasar", value: "denpasar", description: "The capital city of Bali Province" },
      { label: "Semarang", value: "semarang", description: "The capital city of Central Java" },
    ],
    posisi: [
      { label: "Software Engineer", value: "software-engineer", description: "A job in software development" },
      { label: "Data Analyst", value: "data-analyst", description: "A job analyzing data trends" },
      { label: "Product Manager", value: "product-manager", description: "A role in product development and management" },
      { label: "Graphic Designer", value: "graphic-designer", description: "A creative role focused on visual content" },
      { label: "Marketing Specialist", value: "marketing-specialist", description: "A role in planning and executing marketing strategies" },
      { label: "HR Manager", value: "hr-manager", description: "A role in managing human resources" },
      { label: "Sales Executive", value: "sales-executive", description: "A role in driving company revenue through sales" },
      { label: "Content Writer", value: "content-writer", description: "A role focused on creating written content" },
      { label: "UX Designer", value: "ux-designer", description: "A role in designing user experiences" },
      { label: "Customer Service", value: "customer-service", description: "A role in handling customer inquiries and issues" },
    ],
    industri: [
      { label: "Technology", value: "technology", description: "A sector focusing on technological advancements" },
      { label: "Healthcare", value: "healthcare", description: "An industry related to health services" },
      { label: "Education", value: "education", description: "An industry focusing on teaching and learning" },
      { label: "Finance", value: "finance", description: "An industry dealing with monetary and investment matters" },
      { label: "Manufacturing", value: "manufacturing", description: "An industry focused on producing goods" },
      { label: "Retail", value: "retail", description: "An industry centered on selling consumer goods" },
      { label: "Hospitality", value: "hospitality", description: "An industry providing services like hotels and tourism" },
      { label: "Construction", value: "construction", description: "An industry focused on building infrastructure" },
      { label: "Transportation", value: "transportation", description: "An industry dealing with the movement of goods and people" },
      { label: "Agriculture", value: "agriculture", description: "An industry focused on farming and producing food" },
    ],
  };
  